PR with finished MVP 1. First attempt.
Gyrf921/meeting-system pull request #1
Opened 2023-07-14 18:59 UTC by Gyrf921

The main methods of the service layer are made. the test coverage of the service layer is 88%. Swagger for Swagger UI has been added.

2023-07-15 12:58 UTC, RedRad1sh requested changes

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/MeetingDAO.java
> +    public MeetingDAO() {}
Можно добавить @NoArgsConstructor от Lombok

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/MeetingDAO.java
> +    public Long getId() {
У тебя уже есть Getter и Setter от Lombok

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/pom.xml
> +					<source>14</source>
source/target - здесь ты выбираешь версию java под которую скомпилируется jar-ник. У нас 11

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/UserDAO.java
> +    public boolean equals(Object o) {
У Lombok также есть аннотация с готовой реализацией: @EqualsAndHashCode

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/MeetingServiceImpl.java
> +    @Autowired
@Autowired лучше заменить на инжект в конструкторе, типа такого:
MeetingServiceImpl(MeetingRepository meetingRepository, ParticipantRepository participantRepository)
Способ через аннотацию использует рефлексию, поэтому через конструктор предпочтительнее

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/MeetingServiceImpl.java
> +        return meetingRepository.findById(id);
Логирование входов и выходов обязательно

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/MeetingServiceImpl.java
> +        Optional<MeetingDAO> meetingDAO = meetingRepository.findById(id);
Где мои логи?

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +        return participantRepository.findAllByMeetingId(meeting_id);
Логи

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +    private ParticipantRepository participantRepository;
Заменить на инжектинг через конструктор

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +        log.info("try to create List<ParticipantDAO> with a lot of users with this meeting info: {} | this users {} | and this userOrganizer {}", meetingDTO, userDAOList, userOrganizer);
Не стоит так подробно входной лог расписывать. В принципе достаточно будет такого единого формата: "[имяметода] >> param1: [param1], param2: [param2]" - входной лог
[имяметода] << result: [result]" - входной лог
Давай для входных и выходных логов на всех остальных заданиях будет такой формат.

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +                throw new ResourceNotFoundException("Someone user is not founded");
Перед выбрасыванием ошибки тоже логировать

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +
log.error("Log was not found");

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/MeetingDAO.java
> +public class MeetingDAO {
Это не DAO, а Entity (можно в принципе убрать из названия DAO). 
Постфикс DAO скорее применим в названии репозиториев. А вообще это целый слой приложения, отвечающий за доступ к бд и включающий: интерфейс доступа, сущности.

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/UserService.java
> +    @Transactional
Нужно обоснование, с какой целью везде используется Transactional?

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/MeetingController.java
> +@RequestMapping("/meetingController")
У нейминга REST есть свои правила стиля и семантики
https://tproger.ru/translations/luchshie-praktiki-razrabotki-rest-api-20-sovetov/

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/MeetingController.java
> +    @GetMapping("/getInfoAboutMeeting/{id}")
В CRUD операциях REST мы оперируем коллекциями. Соответственно доступ к коллекции должен происходить примерно таким образом:
GET /entityname/{id}
GET /entityname
POST /entityname
и т.д.
Тип REST запроса и ссылка уже сами по себе должны быть говорящими.

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/MeetingController.java
> +    @GetMapping("/getParticipant/{id}")
Все участники у нас так или иначе принадлежат какой-либо встрече, так что в соответствии со стилем REST:
GET /meetings/{id}/participants

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/UserController.java
> +@RequestMapping("/userController")
Оперируем коллекциями; users из аннотаций ниже перенести сюда вместо userController

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/MeetingDAO.java
> +    private Date datetimeEnd;
Date - устаревший класс, в нем почти все методы Deprecated. Заменить на LocalDate

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/MeetingServiceImplTest.java
> +        given(meetingRepository.findById(meetingDAO.getId()))
Не ошибка: отмечу, что чаще используется не BDDMockito, а другой стиль when/thenReturn. Просто чтобы не удивлялся, если на проектах увидишь другие названия методов. А так выбор стиля - дело вкуса)

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/MeetingServiceImplTest.java
> +        verify(meetingRepository, times(1)).deleteById(userDAO.getId());
Но если уже используешь стиль BDD, то тогда надо до конца без смешивания)
`BDDMockito.verify(meetingRepository).should(times(1)).deleteById(userDAO.getId())`

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/UserDAO.java
> +    public UserDAO() {
@NoArgsConstructor

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +                for (UserDAO user : userDAOList) {
Большая вложенность, читабельность затрудняется. Нужно разбить метод еще на парочку

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +    public List<ParticipantDAO> create(MeetingDTO meetingDTO, List<UserDAO> userDAOList, UserDAO userOrganizer) {
Надо сделать название метода более говорящим

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/ParticipantServiceImpl.java
> +        for (UserDAO user : userDAOList) {
Попробуй использовать здесь Stream Api. В частности методы: stream(), map() и collect()

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/UserServiceImpl.java
> +
Логи

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/MeetingController.java
> +        return participantService.findAllUsersByMeetingId(id);
Немного запутался в том, что делает метод. По названию "getParticipant" выглядит так, что мы получаем одного участника встречи по его id. Но в названии метода - findAllUsersBy**MeetingId**

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private MeetingDTO meetingDTO;
Нужно ли нам целый meetingDTO передавать, если можем передать только id встречи и сделать потом запрос в БД?

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private List<UserDAO> userDAOList;
Что-то у нас в DTO попали сущности слоя DAO. Слой DTO полностью отдельно должен быть

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private UserDAO userOrganizer;
Мы же можем получить организатора встречи, сделав запрос в БД по id встречи, не передавая этот параметр лишний раз в запросе

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/MeetingController.java
> +
Ну и конечно же - логи во всех входах и выходах

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/pom.xml
>  		<spring-cloud.version>2021.0.8</spring-cloud.version>
Надо правильно настроить ".gitignore", чтобы лишние папки (типа .idea) не подгружались

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/MeetingServiceImpl.java
> +package com.shchin.userservice.service;
Имплементации класть в package "impl"

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/exception/ResourceNotFoundException.java
> +import java.io.Serial;
тут что-то лишнее

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/UserServiceImplTest.java
> +}
Тесты на сервисы - хорошо. Но еще нужны тесты на контроллеры с использованием MockMvc. Давай в рамках уже следующего задания потренируешься их писать. 
Для этого нужно будет изучить интеграционные тесты с поднятием контекста Spring - @SpringBootTest, моки бинов спринг - @MockBean

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/ParticipantId.java
> +@Embeddable
Если ты используешь @IdClass, то эта аннотация здесь не нужна.

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/UserServiceImpl.java
> +
Лог выхода

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/UserController.java
> +}
Логи выхода

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/MeetingDTO.java
> +    private Date datetimeStart;
Date заменить на LocalDate

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/ParticipantId.java
> +    public ParticipantId(){}
@NoArgsConstructor

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/UserServiceImpl.java
> +    }
Логи

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/MeetingServiceImpl.java
> +        return meetingDAO;
Логичнее будет вернуть meetingDAO, который вернул метод save

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/MeetingServiceImpl.java
> +                        .build();
В следующих заданиях нужно будет использовать MapStruct для маппинга из DTO в DAO

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/MeetingServiceImplTest.java
> +        assertThat(savedMeeting).isNotNull();
По хорошему, нужно еще везде добавить сравнение сущностей через assertEquals

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/exception/ErrorDetails.java
> +    private Date timestamp;
Date заменить на LocalDate

2023-07-15 12:58 UTC, RedRad1sh commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/MeetingServiceImplTest.java
> +                .build();
Для удобства и более быстрого написания тестов посмотри RandomBeans, крутая штука
https://github.com/rigorio/random-beans

2023-07-15 15:35 UTC, Gyrf921 commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private MeetingDTO meetingDTO;
Нужно, потому что у нас есть метод создания сразу и встречи и добавления участников, для него нужна полная информация, а не только id

2023-07-15 15:38 UTC, Gyrf921 commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private UserDAO userOrganizer;
Это опять же для случая, когда мы хотим создать и встречу и добавить участников одновременно, в целом можно отправлять не самого организатора, а только его Id, но он нужен

2023-07-15 15:39 UTC, Gyrf921 commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/UserServiceImplTest.java
> +}
Я примерно понимаю как их писать, так что всё хорошо
Во всяком случае один тест на тестовое задание в УЦ написал

2023-07-15 15:40 UTC, Gyrf921 commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/ParticipantId.java
> +    public ParticipantId(){}
Делаю конструктор без аргументов руками, потому что слышал, что Hibernate плохо с lombok-ом дружит, исправлю

2023-07-15 15:42 UTC, Gyrf921 commented on meeting-system/user-service/src/test/java/com/shchin/userservice/service/MeetingServiceImplTest.java
> +        verify(meetingRepository, times(1)).deleteById(userDAO.getId());
Я бы и не смешивал, но начал писать через given и н этом тесте он выдавал ошибку, получилось пофиксить только с BDD

2023-07-15 15:42 UTC, Gyrf921 commented on meeting-system/user-service/src/main/java/com/shchin/userservice/dao/MeetingDAO.java
> +    private Date datetimeEnd;
Это я натупил, мне почему то казалось, что в задании указан был Date, я ещё и сам удивился, хпхпххп

2023-07-15 15:43 UTC, Gyrf921 commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/controller/MeetingController.java
> +    @GetMapping("/getParticipant/{id}")
У нас не обязательно участник принадлежит к встрече, он может быть просто создан, но не участвовать, но REST документацию по неймингу ещё почитаю и всё исправлю

2023-07-15 15:46 UTC, Gyrf921 commented on meeting-system/user-service/src/main/java/com/shchin/userservice/service/UserService.java
> +    @Transactional
Я использовал на методах, которые мне показались наиболее опасными. Что-бы не было случая при создании, когда встреча создалась, а пользователи добавиться не могут из-за какой-то ошибки в данных или параллельного запроса к бд

2023-07-15 17:34 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private MeetingDTO meetingDTO;
По названию "ParticipantDTO" выглядит, что мы создаем только участника. Логичнее же будет создать какое-нибудь meetingDTO и уже внутри него вписать список id участников, которых нужно добавить

2023-07-15 17:34 UTC, RedRad1sh commented on meeting-system/user-service/src/main/java/com/shchin/userservice/web/dto/ParticipantDTO.java
> +    private UserDAO userOrganizer;
Хм, я как-то представлял, что при создании встречи организатор сразу привязывается к встрече, соответственно его в БД должно быть возможным найти

2023-07-17 06:37 UTC, RedRad1sh approved these changes

2023-07-20 19:56 UTC, merged